/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: {
          base: '#0d0d14',
          surface: '#13131f',
          card: '#1a1a2e',
          hover: '#1f1f35',
          border: '#2a2a42',
        },
        gold: {
          DEFAULT: '#d4a017',
          light: '#e8b82a',
          dark: '#b8880f',
          muted: 'rgba(212,160,23,0.15)',
        },
        text: {
          primary: '#f0f0f8',
          secondary: '#9090b0',
          muted: '#5a5a7a',
        },
        status: {
          member: { bg: '#1a2e3d', text: '#4a9eca' },
          worker: { bg: '#2d1f3d', text: '#9b6fd4' },
          leader: { bg: '#3d2a1a', text: '#d4844a' },
          newconvert: { bg: '#1a2d1a', text: '#4aaa4a' },
          pending: { bg: '#2d2d1a', text: '#aaaa4a' },
          contacted: { bg: '#1a2d2d', text: '#4aaaaa' },
          converted: { bg: '#1a2d1a', text: '#4aaa6a' },
        },
        primary: '#500088',
        secondary: '#316bf3',
        tertiary: '#003e17',
        background: '#f9f9ff',
        surface: '#f9f9ff',
        'surface-container': '#e9edff',
        'surface-container-low': '#f1f3ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e1e8fd',
        'on-surface': '#141b2b',
        'on-surface-variant': '#4c4452',
        'on-primary': '#ffffff',
        'on-primary-container': '#d7a8ff',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#003ea8',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#005320',
        'primary-container': '#6b21a8',
        'primary-fixed': '#f1dbff',
        'primary-fixed-dim': '#dfb7ff',
        'secondary-container': '#316bf3',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b4c5ff',
        'tertiary-container': '#005823',
        'tertiary-fixed': '#7ffc97',
        'tertiary-fixed-dim': '#62df7d',
        outline: '#7e7383',
        'outline-variant': '#cfc2d4',
        'on-background': '#141b2b',
        'inverse-surface': '#293040',
        'inverse-on-surface': '#edf0ff',
        'inverse-primary': '#dfb7ff',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
      },
      fontFamily: {
        sans: ['"Inter"', 'sans-serif'],
        display: ['"Montserrat"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
        'body-md': ['"Inter"', 'sans-serif'],
        'button-text': ['"Montserrat"', 'sans-serif'],
        'headline-xl': ['"Montserrat"', 'sans-serif'],
        'headline-lg': ['"Montserrat"', 'sans-serif'],
        'headline-md': ['"Montserrat"', 'sans-serif'],
        'headline-sm': ['"Montserrat"', 'sans-serif'],
        'headline-xs': ['"Montserrat"', 'sans-serif'],
        'label-badge': ['"Inter"', 'sans-serif'],
        caption: ['"Inter"', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'button-text': ['15px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-badge': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xs': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'space-4xl': '6rem',
        margin: '2rem',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
      },
      borderRadius: {
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.25rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 2px 20px rgba(0,0,0,0.4)',
        glow: '0 0 20px rgba(212,160,23,0.2)',
        modal: '0 25px 80px rgba(0,0,0,0.7)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-in': 'slideIn 0.25s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-gold': 'pulseGold 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideIn: { from: { opacity: '0', transform: 'translateX(-10px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        pulseGold: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
      },
    },
  },
  plugins: [],
};
